### ISSUE TITLE
Statistics script for task embeddings

### ISSUE THREAD

**Issue by turian** [neuralaudio/hear-eval-kit#104]
Summary statistics of task embedding output

Write a function for luigi that, for a particular directory, crawls it to find all WAV files and outputs stats to a JSON file:
* number of files
* mean, median, 25%, 75%, 10%, and 90% of audio file length

And then we want to run that both on the original WAV directories from extraction and then we want ALSO to run it at the end on the subsampled directories for each split. We will use this to sanity check stuff.

**Comment by jorshi** [comment]
Completed in #123
