### ISSUE TITLE
Missing intervaltree dependency

### ISSUE THREAD

**Issue by auroracramer** [neuralaudio/hear-eval-kit#154]
[heareval/predictions/task_predictions.py](https://github.com/neuralaudio/hear-eval-kit/blob/main/heareval/predictions/task_predictions.py) and [heareval/embeddings/task_embeddings.py](https://github.com/neuralaudio/hear-eval-kit/blob/main/heareval/embeddings/task_embeddings.py) both use the `intervaltree` module, but it is missing from [setup.py](https://github.com/neuralaudio/hear-eval-kit/blob/main/setup.py).

**Comment by turian** [comment]
Thank you, this is in https://github.com/neuralaudio/hear-eval-kit/pull/158
