### ISSUE TITLE
ffmpeg needs to be >= 4.2 for apad options to work properly

### ISSUE THREAD

**Issue by auroracramer** [neuralaudio/hear-eval-kit#155]
If `ffmpeg` < 4.2 (according to [this issue](https://trac.ffmpeg.org/ticket/8052)), then the `whole_dur` argument for `apad` is not recognized in the subprocess call to `ffmpeg` in [mono_wav_and_fix_duration](https://github.com/neuralaudio/hear-eval-kit/blob/main/heareval/tasks/util/audio.py#L18), which results in a non-zero exit code (1) and makes the assertion fail. The version I was using is `ffmpeg==3.4.8` on Ubuntu 18.04, but the issue went away after upgrading to 4.3.2 (via the package on conda-forge).

It would be good to specify in the documentation so users know to have `ffmpeg >= 4.2` installed.

**Comment by turian** [comment]
Great find! This is in https://github.com/neuralaudio/hear-eval-kit/pull/158
