### ISSUE TITLE
nsynth metadata columns are missing

### ISSUE THREAD

**Issue by auroracramer** [neuralaudio/hear-eval-kit#157]
[This assertion](https://github.com/neuralaudio/hear-eval-kit/blob/main/heareval/tasks/pipeline.py#L252) fails when running `python -m heareval.tasks.runner nsynth_pitch`:

```
Traceback (most recent call last):
  File "/ext3/miniconda3/lib/python3.9/site-packages/luigi/worker.py", line 191, in run
    new_deps = self._run_get_new_deps()
  File "/ext3/miniconda3/lib/python3.9/site-packages/luigi/worker.py", line 133, in _run_get_new_deps
    task_gen = self.task.run()
  File "/ext3/code/hear-eval-kit/heareval/tasks/pipeline.py", line 242, in run
    assert set(
AssertionError
```

It may be due to the last line of [nsynth_pitch.ExtractMetadata.get_split_metadata](https://github.com/neuralaudio/hear-eval-kit/blob/ca210b9e3b52fec4cc5f37aa8c2a38374ffa8d0f/heareval/tasks/nsynth_pitch.py#L100) omitting the `split_key` and `stratify_keys` expected when processing metadata for scene embeddings.

**Comment by khumairraj** [comment]
Thank you @auroracramer for bringing this up. 
The solution is in fact to just return all the columns in the last line [nsynth_pitch.ExtractMetadata.get_split_metadata](https://github.com/neuralaudio/hear-eval-kit/blob/ca210b9e3b52fec4cc5f37aa8c2a38374ffa8d0f/heareval/tasks/nsynth_pitch.py#L100) by changing the line to be just  `return metadata`

The nsynth data is indeed very large and I couldn't get beyond the download task. However, I am working on a smaller version of all datasets that could help us with setting up CI/CD. I will fix this issue in the same pr and also run end to end for nsynth.

**Comment by khumairraj** [comment]
#160 fixes this.

**Comment by turian** [comment]
@auroracramer closing the issue but please comment or open another issue as you need
