### ISSUE TITLE
Allow for output directories to be configured

### ISSUE THREAD

**Issue by auroracramer** [neuralaudio/hear-eval-kit#159]
The output folders `_workdir`, `tasks`, `embeddings`, and `predictions`  are all created in the current directory. However, given that significant data is downloaded/generated it'd be useful to select the output directories (which may be on a different volume with more disk space).

**Comment by turian** [comment]
@auroracramer this sounds like a good request, we will address it.

**Comment by turian** [comment]
@auroracramer this was fixed a few days ago, can you check that it works for you?

**Comment by turian** [comment]
@auroracramer this is fixed. Preprocessing code is all in `hear-preprocess` repo now. If you have any more questions or comments, feel free to re-open or open a new issue.
