### ISSUE TITLE
Preprocessing fails

### ISSUE THREAD

**Issue by wanglouis49** [neuralaudio/hear-eval-kit#285]
Hi there, first thanks for creating this challenge!

I was trying to run this eval kit today. However, when preprocessing the tasks using `python3 -m heareval.tasks.runner all`, it ends up with:

```
===== Luigi Execution Summary =====

Scheduled 84 tasks of which:
* 42 ran successfully:
    - 7 DownloadCorpus(...)
    - 7 ExtractArchive(...)
    - 3 ExtractMetadata(...)
    - 1 GenerateTrainDataset(...)
    - 3 MetadataVocabulary(...)
    ...
* 36 failed:
    - 36 ResampleSubcorpus(...)
* 6 were left pending, among these:
    * 6 had failed dependencies:
        - 3 FinalizeCorpus(...)
        - 3 ResampleSubcorpuses(...)

This progress looks :( because there were failed tasks
```

I saw lots of AssertionError saying the resampling has filed (like this one):

```
File "/home/luyuwang/hear-eval-kit/heareval/tasks/pipeline.py", line 737, in run
    audio_util.resample_wav(audiofile, resampled_audiofile, self.sr)
  File "/home/luyuwang/hear-eval-kit/heareval/tasks/util/audio.py", line 79, in resample_wav
    assert ret == 0
AssertionError
```

Any suggestion how can I properly process the data?

**Comment by turian** [comment]
@wanglouis49 Thank you for participating!

* The preprocessed data sets will be provided for https download soon, so you won't need to run preprocessing yourself.
* Preprocessing is moving to the hear-preprocess. This repo you can use for evaluation your model on the open tasks.

Please check back in this repo at the beginning of next week

**Comment by turian** [comment]
@wanglouis49 we have now released preprocessed versions of the open dataset. I will close this issue. Please re-open or open a new issue if you have additional questions or comments
