### ISSUE TITLE
Timestamps for centered frames

### ISSUE THREAD

**Issue by jorshi** [neuralaudio/hear-eval-kit#36]
I don't think there's a need for this. Timestamps will be the same whether or not the frames are centered.

_Originally posted by @maxsolomonhenry in https://github.com/neuralaudio/hear2021-eval-kit/pull/2#discussion_r642485576_

**Comment by turian** [comment]
```
center = 0
framenumber = 0
while center < audio_samples:
    frame = [center - frame_width, center + frame_width]
    center = int(round(sample_rate * framenumber / framerate))
```

**Comment by turian** [comment]
We probably don't want to support non-centered frames, only centered frames. We should update the API doc to reflect that.
