### ISSUE TITLE
Create a tutorial document -- Jupyter Book?

### ISSUE THREAD

**Issue by jorshi** [neuralaudio/hear-eval-kit#57]
Should have the following components:

•Background and motivation (from proposal doc)
•Summary of relevant prior works and synthesis of general trends in the literature, both in audio as well as adjacent ML fields whose progress in representation learning has not yet been borne out in audio ML research.
•A high-level description of the variety of domains and tasks that the model will be evaluated  on.   A  particular  emphasis  will  be  made  on  high  societal  impact  audio tasks that are currently underrepresented, such as low-resource languages, environ-mental and ecological safety, clinical speech applications, and ethnomusicology, thus encouraging participants to devise impactful datasets rather than relying solely upon popular and/or commercially viable benchmarks.

**Comment by turian** [comment]
This is more like overleaf than a Jupyter book
