### ISSUE TITLE
Multi-class evaluation.

### ISSUE THREAD

**Issue by jorshi** [neuralaudio/hear-eval-kit#59]
Implement evaluation metric for multi-class evaluation predictions using MRR.

**Comment by turian** [comment]
Where is the cite that MRR is standard for multi-class challenges? (Why not use NDCG?)

Also, AUC seems reasonable too

**Comment by jorshi** [comment]
@maxsolomonhenry

**Comment by jorshi** [comment]
Top-1 and AUC implemented in #143
